version: '3'

services:
  freedrive:
    image: marcinx98x/freedrive:latest
    container_name: freedrive
    restart: unless-stopped
    user: "0:0"
    ports:
      - "8080:8080"
    environment:
      - FREEDRIVE_ADMIN_EMAIL=admin@twoj-domena.com
      - FREEDRIVE_ADMIN_PASSWORD=BardzoSilneHaslo123!
      - FREEDRIVE_MAX_UPLOAD_MB=10240
    volumes:
      - /volume2/docker/freedrive/data:/app/data
